namespace Mercraft.Maps.Osm.Pbf
{
    /// <summary>
    /// An object that implements this interface can consume objects generated by the PBFReader.
    /// </summary>
    internal interface IPbfPrimitiveBlockConsumer
    {
        /// <summary>
        /// Processes a primitive block of OSM data.
        /// </summary>
        /// <param name="block"></param>
        void ProcessPrimitiveBlock(PrimitiveBlock block);
    }
}